// Top-level build file — NE PAS appliquer de plugin Flutter ici.
buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:8.6.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Tâche clean simple
tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
